---

- name: Make sure python2 as pre-requisites are installed.
  yum:
    name: 
      - python2
      - compat-openssl10
    state: present

- name: Make python2 the default python interpreter
  alternatives:
    name: python2
    link: /usr/bin/python2
    path: /usr/bin/python2
