---
- hosts: localhost
  become: yes
  roles:
    - { role: ansible-role-mssql }
  tasks:
    - name: Wait up to 60 seconds for server to become available after creation
      wait_for:
        port: 1433
        timeout: 60
    - name: Create new db
      include_role:
        name: ansible-role-mssql
        tasks_from: new_db
