# These are required for database installation
end_user_license_aggreement_consent_server: Y # Must be Y or N
end_user_license_aggreement_consent_cli: "YES" # Must be YES or NO in all caps within quotes
edition: evaluation

# For use when creating, importing, or deleting databases
db_name: meetup_db
db_host: 127.0.0.1
db_port: 1433
db_user: sa
db_password: P@ssWORD!
